config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'static_pages/about'

  get 'static_pages/contact'

  resources :exercises

  resources :workouts do
    resources :instructions
  end

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  has_many :instructions
  has_many :workouts, through: :instructions

  scope :quads, -> { where(muscle_group: "quads") }
  scope :hamstrings, -> { where(muscle_group: "hamstrings") }
  scope :glutes, -> { where(muscle_group: "glutes") }
  scope :calves, -> { where(muscle_group: "calves") }

end

app/models/instruction.rb
class Instruction < ActiveRecord::Base
  belongs_to :workout
  belongs_to :exercise
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  has_many :instructions
  has_many :exercises, through: :instructions

  accepts_nested_attributes_for :instructions



  # scope :quads, -> { where(muscle_group: "quads") }
  # scope :hamstrings, -> { where(muscle_group: "hamstrings") }
  # scope :glutes, -> { where(muscle_group: "glutes") }
  # scope :calves, -> { where(muscle_group: "calves") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only:[:show, :edit, :update, :destroy]

  def index
    @exercises = Exercise.all
  end

  def show
  end

  def new
    @exercise = Exercise.new
  end

  def create
    @exercise = Exercise.new(exercise_params)
    if @exercise.save
      redirect_to @exercise
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @exercise.update_attributes(exercise_params)
      redirect_to @exercise
    else
      render :edit
    end
  end

  def destroy
    @exercise.delete
    redirect_to exercise_path
  end

  private

    def exercise_params
      params.require(:exercise).permit(:name, :description, :muscle_group)
    end

    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  def index
    @workouts = Workout.all
  end

  def show
  end

  def new
    @workout = Workout.new
    instruction = @workout.instructions.build
    instruction.exercises.build
  end

  def create
    @workout = Workout.create(workout_params)
    # @instruction = @workout.instructions.build
    if @workout.save
      redirect_to @workout
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @workout.update_attributes(workout_params)
      redirect_to @workout
    else
      render :edit
    end
  end

  def destroy
    @workout.delete
    redirect_to @workouts
  end

  private

  def workout_params
    params.require(:workout).permit(:name, instructions_attributes: [:id, :sets, :reps, :duration, :weight, :workout_id, :exercise_id, :_destroy])
  end

  def set_workout
    @workout = Workout.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/edit.html.erb
<h1>Exercises#edit</h1>
<p>Find me in app/views/exercises/edit.html.erb</p>

app/views/exercises/index.html.erb
<h1>Exercises</h1>
<% @exercises.each do |exercise| %>
  <ul class="list-group">
    <li class="list-group-item"><h5>Name:</h5> <%= exercise.name %></li>
    <li class="list-group-item"><h5>Description:</h5> <%= exercise.description %></li>
    <li class="list-group-item"><h5>Muscle Group:</h5> <%= exercise.muscle_group %></li>
  </ul>
  <% end %>

app/views/exercises/show.html.erb
<h1>Exercises#show</h1>
<p>Find me in app/views/exercises/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <div class="row">
    <%= yield %>
  </div>
  </body>
</html>

app/views/static_pages/_form.html.erb
<h1>Build a Workout</h1>

<%= simple_form_for @exercises do |f| %>

  <%= f.input :muscle_group, as: :select, collection: Exercise.quads %>

  <%= f.submit %>

<% end %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Build a Workout</h1>
<%= render 'form' %>

app/views/workouts/_form.html.erb
<%= simple_form_for(@workout) do |f| %>
  <%= f.input :name %>

  <%= f.simple_fields_for :instructions do |instruction| %>
    <%= render 'instruction_fields', :f => instruction %>
  <% end %>

  <%# link_to_add_association 'Add an Exercise', f, :instructions %>

  <%= f.submit %>
<% end %>

app/views/workouts/_instruction_fields.html.erb
<div class="nested_fields">
  <% @exercises = Exercise.all %>
  <% @quads = Exercise.quads %>
  <% @hamstrings = Exercise.hamstrings %>
  <% @calves = Exercise.calves %>

    <%= f.label :exercise_id, collection: @quads, :label_method => :name, :value_method => :id, label: 'Quads'  %>
    <%= f.input :sets, label: 'sets'  %>
    <%= f.input :reps, label: 'reps'  %>
    <%# f.label :exercise_id, collection: @hamstrings, :label_method => :name, :value_method => :id, label: 'Hamstrings'  %>
    <%# f.input :sets, label: 'sets'  %>
    <%# f.input :reps, label: 'reps'  %>
    <%# f.label :exercise_id, collection: @calves, :label_method => :name, :value_method => :id, label: 'Calves'  %>
    <%# f.input :sets, label: 'sets'  %>
    <%# f.input :reps, label: 'reps'  %>

</div>

app/views/workouts/edit.html.erb
<h1>Build a Workout</h1>

  <%= render 'form' %>

app/views/workouts/index.html.erb
<h1>Workouts#index</h1>
<p>Find me in app/views/workouts/index.html.erb</p>

app/views/workouts/new.html.erb
<h1>Build a Workout</h1>

  <%= render 'form' %>

app/views/workouts/show.html.erb
<h1>Workout</h1>


<%= @workout.name %>

<% @workout.instructions.each do |r| %>
  <%= r.exercise.name %>
  <%= r.exercise.description %>
  <%= r.sets %>
  <%= r.reps %>
<% end %>
<%= link_to "Edit", edit_workout_path(@workout) %>